agora/urls.py
from django.urls import path, include
from django.contrib import admin
from agora import views
from django.conf import settings
from django.conf.urls.static import static

# from todolist.urls import urlpatterns

urlpatterns = [
    path(r'', views.login_redirect, name='login_redirect'),
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('modules.accounts.urls', namespace='accounts')),
    path(r'home/', include('modules.home.urls', namespace='home')),
    path(r'business/', include('modules.business.urls', namespace='business')),
    path(r'items/', include('modules.items.urls', namespace='items')),
    path(r'todolist/', include('modules.todolist.urls', namespace='todolist')),
    path(r'partners/', include('modules.partners.urls', namespace='partners')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/accounts/urls.py
from django.urls import path, include
from . import views # . will look into docs with the name views in this file this 
from django.contrib.auth.views import (
login, logout, 
password_reset, password_reset_done,
password_reset_confirm, password_reset_complete)# get login vi
from rest_framework import routers
from .views import UserViewSet

router = routers.DefaultRouter()
router.register(r'v1/users/', views.UserViewSet),
router.register(r'v1/userprofiles/', views.UserProfileViewSet)



app_name = 'accounts'

	
urlpatterns = [
    path(r'login/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path(r'logout/', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    path(r'register/', views.register, name='register'),
    path(r'profile/', views.view_profile, name='view_profile'),
    path(r'profile/<int:pk>/', views.view_profile, name='view_profile_with_pk'),
    path(r'profile/edit/', views.edit_profile, name='edit_profile'),
    path(r'change-password/', views.change_password, name='change_password'),

    path(r'reset-password/', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    path(r'reset-password/done/', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    path(r'reset-password/confirm/(<uidb64>[0-9A-Za-z]+)-(<token>.+)/', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    path(r'reset-password/complete/', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
    
    path(r'api/', include(router.urls)),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path(r'api-detail/',views.UserDetailView )

]

modules/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


'''class UserProfileManager(models.Manager):
	def  get_queryset(self):
		return super(UserProfileManager, self).get_queryset().filter(city='CDMX')'''

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	description = models.CharField(max_length=100, default='')
	city = models.CharField(max_length=100,default='')
	website = models.URLField(default='')
	phone = models.IntegerField(default=0)
	#image = models.ImageField(upload_to= 'profile_image', blank = True)

	#CDMX=UserProfileManager()

	def __str__(self):
		return self.user.username


def create_profile(sender,**kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

modules/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile


class RegistrationForm(UserCreationForm):
	email=forms.EmailField(required=True)

	class Meta: 
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
		)

	def save(self, commit=True):#save in database
		 user = super(RegistrationForm,self).save(commit=False)
		 user.first_name = self.cleaned_data['first_name']
		 user.last_name = self.cleaned_data['last_name']
		 user.email = self.cleaned_data['email']

		 if commit:
		 	user.save()

		 return user

class EditProfileForm(UserChangeForm):
	
	class Meta: # exlude fields in a model
		model = User
		fields = (
			'email',
			'first_name',
			'last_name',
			
			)

modules/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from modules.accounts.forms import (
    RegistrationForm,
    EditProfileForm
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import viewsets
from .serializers import UserSerializer, UserProfileSerializer
from .models import UserProfile
from rest_framework.views import APIView

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST.get('username')
            password = request.POST.get('password1')

            user = authenticate(
                username=username,
                password=password
            )
            login(request,user)


            return redirect(reverse('home:home'))
    else:
        form = RegistrationForm()

    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)

def view_profile( request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile( request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)



# ----------------------API---------------------------------

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

class UserProfileViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer



class UserDetailView(APIView):
    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        serializer = User(user)
        return Response(serializer.data)

class UserProfileDetailView(APIView):
    def get(self, request, pk):
        userprofile = get_object_or_404(UserProfile, pk=pk)
        serializer = User(userprofile)
        return Response(serializer.data)

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
	<form method="post">
		{% csrf_token %}
		{{ form.as_ul }}
		<button type ="submit" class="btn btn-primary">Submit</button>
	</form>
	<br>
</div>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type ="submit" class="btn btn-primary">Submit</button>
	</form>
	<br>
</div>

{% endblock %}

templates/accounts/login.html
{% extends  'base.html' %}

{% block body %}



<!-- Form Name -->


<div class="d-flex justify-content-center">
	
	<fieldset>
	<h1>Welcome</h1>
	<p>
		You can login here
	</p>
	<h2>Login</h2>
	<form method="post">
		 {% csrf_token %} 			<!-- crear un tolken para que sea seguro hacer el login en la pagina es obligatorio-->
		 {{form.as_p}}
		 <button type="submit" class="btn btn-primary">Login</button>
	</form>
	</fieldset>
</div>
	{% endblock %}

templates/accounts/logout.html
{% extends  'base.html' %}

{% block body %}
<div class="d-flex justify-content-center">
	<fieldset>
	<h1>See you soon</h1>

	
	<p>
		You have logged out
	</p>
	</fieldset>
</div>
	{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %} 

{% block head %}
<title>Profile</title>
{% endblock %}

{% block  body %}
<div class ="container">

Bienvenido {{user.first_name}}{{user.last_name}}, aqui podras administrar todas tus compras y controlar que información quieres compartir 
<hr>
	{% if user.userprofile.image %}
	<img src="{{ user.userprofile.image }}" width="240"
	>
	{% endif %}
	<p>Username: {{ user }}</p>
	<p>Email: {{ user.email }}</p>
	<p>Contacto : {{ user.userprofile.phone }}</p>
	<p>City : {{ user.userprofile.city }}</p>

	<p> {{ user.b2cprofile.business_name }}</p>
	</p>
</div>
{% endblock %}

templates/accounts/reg_form.html
{% extends  'base.html' %}

{% block body %}



<!-- Form Name -->



<div class="d-flex justify-content-center">
	
	<fieldset>
	<h1>Welcome to AGORAD</h1>
	<p>
		Find out what the world has to offer 
	</p>

	<form method="post">
		 {% csrf_token %} 			<!-- crear un tolken para que sea seguro hacer el login en la pagina es obligatorio-->
		 {{form.as_p}}
		 <button type="submit" class="btn btn-primary"> Sign Up</button>
	</form>
	</fieldset>
</div>
	{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class='container'>
	<h1>Password reset</h1>
	<p>
		Forgotten your password? Enter your email below, and we'll mail you firther instructions for set in a new one.
	</p>
	<form method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary"> Reset password</button>
	</form>
</div>
{% endblock %}

templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class='container'>
	<h1>Password reset sent</h1>
	<p>
		Forgotten your password? Enter your email below, and we'll mail you firther instructions for settinf a new one.
	</p>
	</form>
	<a href="{% url 'accounts: login'%">Login</a>
</div>
{% endblock %}

templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class='container'>
	<h1>Enter new Password</h1>
	<p>
		
	</p>
	<form method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit"> Reset password </button>
	</form>
</div>
{% endblock %}

templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class='container'>
	<h1>Password reset sent</h1>
	<p>
		Forgotten your password? Enter your email below, and we'll mail you firther instructions for settinf a new one.
	</p>
	</form>
</div>
{% endblock %}

templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}