agora/urls.py
from django.urls import path, include
from django.contrib import admin
from agora import views
from django.conf import settings
from django.conf.urls.static import static

# from todolist.urls import urlpatterns

urlpatterns = [
    path(r'', views.login_redirect, name='login_redirect'),
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('modules.accounts.urls', namespace='accounts')),
    path(r'home/', include('modules.home.urls', namespace='home')),
    path(r'business/', include('modules.business.urls', namespace='business')),
    path(r'items/', include('modules.items.urls', namespace='items')),
    path(r'todolist/', include('modules.todolist.urls', namespace='todolist')),
    path(r'partners/', include('modules.partners.urls', namespace='partners')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/business/urls.py
from django.urls import path, include

from . import views
from .views import ( 
B2cDetailsView,
BusinessCreateView,
BusinessUpdateView,
B2cApiDetailsView
	)
from rest_framework import routers

router = routers.DefaultRouter()

router.register(r'v1/b2cprofiles', views.B2cProfileViewSet),
# router.register(r'b2c/<int:pk>/', views.B2cApiDetailsView)

app_name = 'business'

urlpatterns = [
	path(r'b2c/register/', views.register, name='register'),
	path(r'b2c/create/', BusinessCreateView.as_view(), name='create'),
	path(r'b2c-profile/', views.view_b2c_profile, name='view_profile'),
    path('<slug:slug>/', views.B2cDetailsView.as_view(), name='detail'),
    path(r'<slug:slug>/edit/', BusinessUpdateView.as_view(), name='edit'),
    path(r'api/', include(router.urls)),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path(r'api/<int:pk>/', views.B2cApiDetailsView),
   ]

modules/business/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.models import User
from modules.accounts.models import UserProfile
from django.db.models.signals import post_save
from .utils import unique_slug_generator
from django.urls import reverse



B_CATEGORIES = (
    ("Comida y Bebida","Comida y Bebida"),
    ("Salud y Bienestar","Salud y Bienestar"),
    ("Ropa y Accesorios","Ropa y Accesorios"),
    ("Energía","Energía"),
    ("Arte","Arte"),
    ("Artículos para el Hogar","Aartículos para el Hogar"),
    ("Artículos para Oficina","Artículos para Oficina"),
    ("Atículos Electrónicos","Artículos Electrónicos"),
    ("Juguetes","Juguetes"),
    ("Automóviles","Automóviles"),
    ("Ventas al por Menor","Ventas al por Menor"),
    ("Libros","Libros"),
    ("Serivicios Publicitarios","Servicios Publicitarios"),
    ("Cosmética y Cuidado Personal","Cosmética y Cuidado Personal"),
    ("Artículos Deportivos","Artículos Deportivos"),
    ("Servicios de Limpieza","Sercicios de Limpieza"),
    ("Ventas al por Mayor","Ventas al por Mayor"),
    ("Servicios Empresariales","Servicios Empresariales"),
    ("Servicios de Paquetería","Servicios de Paquetería"),
    ("Servicios Financieros","Servicios Financieros"),
    ("Servicios Bancarios","Servicios Bancarios"),
    ("Organización de Eventos","Organizaciónde de Eventos"),
)

'''class UserProfileManager(models.Manager):
	def  get_queryset(self):
		return super(UserProfileManager, self).get_queryset().filter(city='CDMX')'''

class B2cProfile(models.Model):
	
	image		    = models.ImageField(upload_to='', null=True, blank=True)  
	owner 			= models.OneToOneField(User, on_delete=models.CASCADE)
	created 		= models.BooleanField(default=True)
	business_name 	= models.CharField(max_length=100,default='')
	description 	= models.TextField(max_length=240, default='')
	location 		= models.CharField(max_length=100,default='')
	website			= models.URLField(default='')
	phone 			= models.IntegerField(default=0)
	apertura		= models.CharField(max_length=100, default='')
	cierre 			= models.CharField(max_length=100, default='')	
	slug            = models.SlugField(null=True, blank=True)
	category   	    = models.CharField(max_length=50,choices= B_CATEGORIES)
	
	def __str__(self):
			return self.business_name 

	# def __unicode__(self):
 #    		return unicode(self.owner)

 

	def get_absolute_url(self): #get_absolute_url
	        #return f"/restaurants/{self.slug}" 
	    return reverse('business:detail', kwargs={'slug': self.slug})

    # @property
    # def title(self):
    #     return self.name


# def create_b2cprofile(sender,**kwargs):
# 	if kwargs['created']:
# 		b2c_profile = B2cProfile.objects.create(user=kwargs['instance'])

# post_save.connect(create_b2cprofile, sender=User)


	@property
	def title(self):
		return self.business_name


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    # instance.category = instance.category.capitalize()
	# print ('savings..')
	# print(instance.timestamp)
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

# def rl_post_save_receiver(sender, instance, created,  *args, **kwargs)
# 	print ('savings..')
# 	print(instance.timestamp)
# 	if not instance.slug:
# 		instance.slug = unique_slug_generator(instance)
# 		instance.save()

pre_save.connect(rl_pre_save_receiver, sender= B2cProfile)




def get_absolute_url(self): 
         
    return reverse('business:detail', kwargs={'pk': self.pk})

modules/items/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from modules.business.models import B2cProfile



class Item(models.Model):
    # associations
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    business      	= models.ForeignKey(B2cProfile, on_delete=models.CASCADE)
    name            = models.CharField(max_length=120)
    description     = models.TextField(max_length = 280)
    extra_info      = models.TextField(max_length = 280)
    politicas       = models.TextField(max_length = 280)
    price           = models.IntegerField(default=0)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self): 
         
        return reverse('items:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

modules/business/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import B2cProfile

# CATEGORY_CHOICES =(('SEL','Vender'),('LEN','Prestar'),('GAW','Regalar'),('REN','Rentar'),('INT','Intercambiar'))

class B2cRegisterForm(forms.Form):
	
	business_name = forms.CharField(max_length=100)
	description = forms.CharField(widget=forms.Textarea)
	location = forms.CharField(max_length=100)
	website = forms.URLField()
	phone = forms.IntegerField()
	apertura = forms.CharField(max_length=100)
	cierre = forms.CharField(max_length=100)
	
	# categoria = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices = CATEGORY_CHOICES)	

class BusinessCreateForm(forms.ModelForm):
    #email           = forms.EmailField()
    # category         = forms.CharField(required=False, validators=[validate_category])
    class Meta:
        model = B2cProfile
        fields = [
        	'image',
            'business_name',
			'description' ,
			'location',
			'website', 
			'phone' ,
			'apertura', 
			'cierre', 
			'category',

         
        ]

modules/business/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from modules.accounts.forms import (
    RegistrationForm, 
    EditProfileForm
) #Django user creation form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import B2cRegisterForm, BusinessCreateForm
from .models import B2cProfile
from django.views.generic import DetailView, CreateView, UpdateView
from modules.items.models import Item
from .models import B2cProfile
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import viewsets
from .serializers import B2cProfileSerializer
from rest_framework.views import APIView
# Create your views here.
# here comes all de logic 
'''def home (request):
    #return render(request, 'accounts/login.html')
    #querys
    numbers =[1,2,3,4,5]
    name='Carlos Bárcena
    args={'myName':name, 'numbers':numbers} # dictionary object
    return render(request,'accounts/home.html', args)'''

def register(request):
    form = B2cRegisterForm(request.POST or None)
    errors = None
    if form.is_valid():
        obj =B2cProfile.objects.create(
            business_name = my_b2c.cleaned_data['business_name'],
            description = my_b2c.cleaned_data['description'],
            city = my_b2c.cleaned_data['website'],
            website = my_b2c.cleaned_data['phone'],
            phone = my_b2c.cleaned_data['phone'],
            cierre = my_b2c.cleaned_data['cierre'],
            apertura = my_b2c.cleaned_data['apertura'],
            )
        return redirect("/")
    if form.errors:
        errors= form.errors

    template_name='business/reg_b2c.html'
    context = {"form":form, "errors":errors}
    return render(request, template_name, context)
    # my_b2c = B2cRegisterForm()
    # if request.method == 'POST':
    #     my_b2c = B2cRegisterForm(request.POST,request.FILES)
    #     if my_b2c.is_valid():

    #         business = B2cProfile.objects.create(

    #                 business_name = my_b2c.cleaned_data['business_name'],
    #                 description = my_b2c.cleaned_data['description'],
    #                 city = my_b2c.cleaned_data['website'],
    #                 website = my_b2c.cleaned_data['phone'],
    #                 phone = my_b2c.cleaned_data['phone'],
    #                 cierre = my_b2c.cleaned_data['cierre'],
    #                 apertura = my_b2c.cleaned_data['apertura'],
    #                 )

    #         user = User.objects.get(pk=request.user.id)

         
    #         user.business = business
    #         user.save()
    #         return redirect('/')
    # return render(request, 'business/reg_b2c.html', {'my_b2c':my_b2c})

def view_b2c_profile(request):

    business = B2cProfile.objects.all()
    return render(request,'base.html',{'business':business})


# def business_view_list(request):
#     template_name ='snippets/b2c_list.html'
#     queryset=B2cProfile.objects.all()
#     context = {
#          "object_list":queryset
#     }
#     return render(request, template_name, context)


class B2cDetailsView(DetailView):
     queryset = B2cProfile.objects.all()

    # def get_object(self):
    #     business = self.kwargs.get("business_name")
    #     if username is None:
    #         raise Htt

     # def get_queryset(self):
     #     return Item.objects.filter(user=self.request.business)

    # def get_context_data(self, *args, **kwargs):
    #   print(self.kwargs)
    #   context= super(RestaurantDetailsView, self).get_context_data(*args, **kwargs)
    #   print(context)
    #   return context

    # def get_object(self, *args, **kwargs):
    #     slug = self.kwargs.get('slug')
    #     obj= get_object_or_404(B2cProfile, slug=slug)
    #     return obj

    # def get_queryset(self):
    #     return B2cProfile.objects.filter(user=self.request.user)


class BusinessCreateView(LoginRequiredMixin, CreateView):
    form_class = BusinessCreateForm
    template_name = 'business/reg_b2c.html'
    # success_url = '/business/'
    #success_url = "/restaurants/"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(BusinessCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(BusinessCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Restaurant'
        return context

    def get_queryset(self):
        return Item.objects.filter(user=self.request.business)

class BusinessUpdateView(LoginRequiredMixin, UpdateView):
    form_class = BusinessCreateForm
    login_url = '/login/'
    template_name = 'business/b2cprofile_update.html'
    #success_url = "/restaurants/"

    def get_context_data(self, *args, **kwargs):
        context = super(BusinessUpdateView, self).get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        return B2cProfile.objects.filter(owner=self.request.user)




# ----------------------API---------------------------------


class B2cProfileViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = B2cProfile.objects.all()
    serializer_class = B2cProfileSerializer




class B2cApiDetailsView(APIView):
    def get(self, request, pk):
        b2c = get_object_or_404(B2cProfile, pk=pk)
        serializer = B2cProfileSerializer(b2c)
        return Response(serializer.data)


    # def delete(self, request, pk):
    #     todo = get_object_or_404(ToDo, pk=pk)
    #     todo.delete()
    #     return Response(status=status.HTTP_204_NO_CONTENT)

modules/todolist/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response  import Response

from .serializers import ToDoSerializer
from .models import ToDo




class ToDoListView(APIView):
    def get(self, request):
        todos = ToDo.objects.all()
        serializer = ToDoSerializer(todos, many=True)

        return Response(serializer.data)

    def put(self, request):
        serializer = ToDoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ToDoDetailView(APIView):
    def get(self, request, pk):
        todo = get_object_or_404(ToDo, pk=pk)
        serializer = ToDoSerializer(todo)
        return Response(serializer.data)

    def delete(self, request, pk):
        todo = get_object_or_404(ToDo, pk=pk)
        todo.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

templates/business/b2c_profile.html
{% extends 'base.html' %} 

{% block head %}
<title>Profile</title>
{% endblock %}

{% block  body %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing:border-box}

.mySlides {display:none}

/* Slideshow container */
.slideshow-container {
  width: 1450px;
  position: relative;
  margin: auto;

}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  cursor:pointer;
  height: 13px;
  width: 13px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active, .dot:hover {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1000s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}
</style>
</head>
<body>

<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 3</div>
  <img src="https://www.w3schools.com/css/trolltunga.jpg" style="width:100%">
  <div class="text">Caption Text</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 3</div>
  <img src="https://www.w3schools.com/css/trolltunga.jpg" style="width:100%">
  <div class="text">Caption Two</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 3</div>
  <img src="https://www.w3schools.com/css/trolltunga.jpg" style="width:100%">
  <div class="text">Caption Three</div>
</div>

<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
<a class="next" onclick="plusSlides(1)">&#10095;</a>

</div>
<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
</div>




<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
</script>


<div class ="container">

<p>Username: {{ user }}</p>

c

templates/business/b2cprofile_detail.html
{% extends 'base.html' %} 


{% block head %}
<title>Profile</title>
{% endblock %}

{% block  body %}


<div class="container">
<div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://static.pexels.com/photos/248797/pexels-photo-248797.jpeg" alt="Los Angeles" width="1450" height="400">
    </div>
    <div class="carousel-item">
      <img src="https://hdwallsource.com/img/2014/5/images-26820-27536-hd-wallpapers.jpg" alt="Chicago" width="1450" height="400">
    </div>
    <div class="carousel-item">
      <img src="https://i.pinimg.com/originals/e2/c2/26/e2c22687ad888f747a3bdcd083f352db.jpg" alt="New York" width="1450" height="400">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>

</div>



<div class="col-sm-6" style="background-color:#FFFFFF;">
<!-- <p>Owner: {{ b2profile.owner }}</p> -->
<div class="row">
<h2 >{{ b2cprofile.business_name }}
{% if user == b2cprofile.owner %}
<h6><a class=" text-muted"  href="/business/{{b2cprofile.slug}}/edit/">Edit</a></h6>
{% endif %}
</h2>
</div>

{% if request.user.is_authenticated %}
<form class='form' method='POST'> {% csrf_token %}
<input type='hidden' name='username' />
<button class='btn btn-primary btn-sm'>Follow</button>
</form>
{% endif %}

  <hr >
  <p class=" text-muted">{{ b2cprofile.category }}</p>
	<p >{{ b2cprofile.description }}</p>

  <hr>
  <p>Location : {{ b2cprofile.location }}</p> 
  <p>Contacto {{ b2cprofile.phone }}</p>
	<p>Site: {{ b2cprofile.website}}</p>
	<p>Horario de servicio {{ b2cprofile.apertura }}-{{ b2cprofile.cierre }}</p>


<label for="input-2" class="control-label">Rate This</label>
<input id="input-2" name="input-2" value="2.5" class="rating-loading">
<script>
$(document).on('ready', function(){
    $('#input-2').rating({
        step: 1,
        starCaptions: {1: 'Very Poor', 2: 'Poor', 3: 'Ok', 4: 'Good', 5: 'Very Good'},
        starCaptionClasses: {1: 'text-danger', 2: 'text-warning', 3: 'text-info', 4: 'text-primary', 5: 'text-success'}
    });
});
</script>
</div>

<hr>

<div class="container-fluid">
  <div class="row">

 
{% block content %}

{% include 'items/item_list.html' %} 

{% endblock %} 
 
 {% for rest in user.b2cprofile.item_set.all %}
  <a href="/items/{{rest.pk}}/">
    <div class="col-lg-4">
      <div class="card" style="margin-bottom: 30px">
        <img class="card-img-top" src="https://www.camboexpo.com/ctg/images/default.jpg" style="height: 200px">
        <div class="card-block" style="margin: 10px">
          </a>

          <h5 class="card-title">{{ rest.name }}  |    {{ rest.price }}</h5>
          <p class="card-subtitle mb-2 text-muted">{{ partner.description }}</p>
          <p class="card-text">{{ obj.description }}</p>
          
        </div>
      </div>
    </div>
 

{% endfor %}
  <!--
 
 <div class="d-flex flex-row"  >
  <div class="card" style="width: 20rem;">
  <div class="card-block" style="margin: 20px">
    <h4 class="card-title">{{ partner.partner_name }}</h4>
    <p class="card-text">{{ partner.description }}</p>
    <a href="{{ partner.webpage }}" class="btn btn-primary">Webpage</a>
  </div>
</div> 

  --></div>
  </div>
</div>

</div>





{% endblock %}

templates/business/b2cprofile_update.html
{% extends "base.html" %}
{% load static %}
{% block title %}New Base Book{% endblock title %}
{% block body %}

<dir class="container">
<h4 class="text-muted">Editar</h4>

<hr>
<div class="d-flex justify-content-center">
<form method = 'POST'>{% csrf_token %}

  {{ form.as_p}}
  <!-- <input type="text" name="name" placeholder="Your title"><br/>
  <input type="text" name="location" placeholder="Location"><br/>
  <input type="text" name="category" placeholder="Category"><br/> -->
  <button type="submit">Save</button>
</form>
</div>
</dir>
{% endblock  %}

templates/business/reg_b2c.html
{% extends "base.html" %}
{% load static %}
{% block title %}New Base Book{% endblock title %}
{% block body %}

<dir class="container">
<h4>Crea tu negocio digital</h4>

<hr>
<div class="d-flex justify-content-center">
<form method = 'POST'>{% csrf_token %}

  {{ form.as_p}}
  <!-- <input type="text" name="name" placeholder="Your title"><br/>
  <input type="text" name="location" placeholder="Location"><br/>
  <input type="text" name="category" placeholder="Category"><br/> -->
  <button type="submit">Save</button>
</form>
</div>
</dir>
{% endblock  %}