agora/urls.py
from django.urls import path, include
from django.contrib import admin
from agora import views
from django.conf import settings
from django.conf.urls.static import static

# from todolist.urls import urlpatterns

urlpatterns = [
    path(r'', views.login_redirect, name='login_redirect'),
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('modules.accounts.urls', namespace='accounts')),
    path(r'home/', include('modules.home.urls', namespace='home')),
    path(r'business/', include('modules.business.urls', namespace='business')),
    path(r'items/', include('modules.items.urls', namespace='items')),
    path(r'todolist/', include('modules.todolist.urls', namespace='todolist')),
    path(r'partners/', include('modules.partners.urls', namespace='partners')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/accounts/urls.py
from django.urls import path, include
from . import views # . will look into docs with the name views in this file this 
from django.contrib.auth.views import (
login, logout, 
password_reset, password_reset_done,
password_reset_confirm, password_reset_complete)# get login vi
from rest_framework import routers
from .views import UserViewSet

router = routers.DefaultRouter()
router.register(r'v1/users/', views.UserViewSet),
router.register(r'v1/userprofiles/', views.UserProfileViewSet)



app_name = 'accounts'

	
urlpatterns = [
    path(r'login/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path(r'logout/', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    path(r'register/', views.register, name='register'),
    path(r'profile/', views.view_profile, name='view_profile'),
    path(r'profile/<int:pk>/', views.view_profile, name='view_profile_with_pk'),
    path(r'profile/edit/', views.edit_profile, name='edit_profile'),
    path(r'change-password/', views.change_password, name='change_password'),

    path(r'reset-password/', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    path(r'reset-password/done/', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    path(r'reset-password/confirm/(<uidb64>[0-9A-Za-z]+)-(<token>.+)/', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    path(r'reset-password/complete/', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
    
    path(r'api/', include(router.urls)),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path(r'api-detail/',views.UserDetailView )

]

modules/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path(r'', views.showB2cHome, name='home'),
   
   # url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends')
]

modules/items/urls.py
from django.urls import path, include
from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView,
    ItemsViewSet

)

from . import views

from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'v1/items/', views.ItemsViewSet)


app_name = 'items'
urlpatterns = [
    path(r'create/',  ItemCreateView.as_view(), name='create'),
    path(r'<int:pk>/edit/', ItemUpdateView.as_view(), name='edit'),
    path(r'<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path(r'', ItemListView.as_view(), name='list'),
    path(r'api/', include(router.urls)),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

modules/partners/urls.py
from django.urls import path
from .views import viewPartners
from . import views

app_name = 'partners'

urlpatterns = [
	
	path(r'', views.viewPartners, name='view_partners'),
   
	]

templates/base.html
<html>
    <head>
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head %}
        <title>¡¡¡¡¡¡¡¡PRUEBA!!!!!</title>
        {% endblock %}
    </head>
    <body>



<nav class="navbar navbar-expand-lg navbar-muted bg-white sticky-top">
  
  <a class="navbar-brand text-muted" href="{% url 'home:home' %}" style="margin-left: 110px">¡¡¡¡¡¡¡¡PRUEBA!!!!!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent" >
    <ul class="navbar-nav mr-auto">
     <!--  <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> -->

      <form class="form-inline my-2 my-lg-0" style="margin-left: 0px" >
      <input class="form-control mr-sm-2" type="search" placeholder="Busca..." aria-label="Search">
      <button type="button" class="btn btn-primary">
      <span class="glyphicon glyphicon-search"></span> Search
    </button>
    </form>

      

</ul>
    
    

    <ul class="nav navbar-nav navbar-right">

      {% if user.b2cprofile.business_name %}


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-muted" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.b2cprofile.business_name }} </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <a  class="nav-link text-muted" href="/business/{{ user.b2cprofile.slug }}/"> Profile </a>
   
  <!--         <div class="dropdown-divider"></div>

          <a  class="nav-link text-muted" href="{{ business.get_absolute_url }}">Perfil2</a> -->


          <div class="dropdown-divider"></div>
          <a class="nav-link text-muted" href="{% url 'todolist:todo' %}">Todolist</a>
          <div class="dropdown-divider"></div>
          <a class="nav-link text-muted" href="{% url 'partners:view_partners' %}">Partners</a>
        </div>
      </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link text-muted" href="{% url 'accounts:view_profile' %}">{{ user.first_name}}</a>
        </li>

        <li class="nav-item dropdown text-muted">
          <a class="nav-link dropdown-toggle text-muted" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-right: 80px">
            Opciones
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
        
          <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit</a>
          <div class="dropdown-divider"></div>
          {% if not user.b2cprofile.business_name %}
        
          <a class="dropdown-item" href="{% url 'business:create' %}">Add Business</a>
           <div class="dropdown-divider"></div>
          {% endif %}

          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
        </div>
        </li>
      </ul>



     {% else %}

<div class="collapse navbar-collapse" id="navbarSupportedContent" >
    <ul class="navbar-nav mr-auto">
     <!--  <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> -->

      <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="" aria-label="">
      <button type="button" class="btn btn-primary">
      <span class="glyphicon glyphicon-search"></span> Search
    </button>
    </form>

      

</ul>
    
    

    <ul class="nav navbar-nav navbar-right" style="margin-right: 80px">

      

        <li class="nav-item">
          <a class="nav-link text-muted" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-muted" href="{% url 'accounts:register' %}">Register</a>
        </li>
       
      </ul>

 
{% endif %}

    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>


<hr style="margin: 0px">

     
<!--         
            <nav class="navbar navbar-default" style="margin-left:0px">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                
                <a class="navbar-brand" style="margin-right: 100px" href="{% url 'home:home' %}" >Agorad </a>
             
            </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                
                    <li><a href="{% url 'business:view_profile' %}"> My Business </a></li>
                    <li><a href="{% url 'todolist:todo' %}">Operation Controll</a></li>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Options
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <p> <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">  Edit</a></p>
         <p> <a class="dropdown-item" href="
          {% url 'business:register' %}">  Add Buiness</a></p>
         <p> <a class="dropdown-item" href="{% url 'accounts:change_password' %}">  Change password</a></p>
         <p> <a class="dropdown-item" href="{% url 'accounts:logout' %}">  Log out</a></p>
        </div>
      </li>
     </ul>           

                  




                
                {% elif user.is_authenticated and business.b2cprofile.user == user %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                      <li><a href="{% url 'business:view_profile' %}"> My Business </a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'todo:todolist' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
               
              </div>
            </div>
        </div> -->
        {% block body %}
        
        {% endblock %}



    </body>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <!-- <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
</html>