agora/urls.py
from django.urls import path, include
from django.contrib import admin
from agora import views
from django.conf import settings
from django.conf.urls.static import static

# from todolist.urls import urlpatterns

urlpatterns = [
    path(r'', views.login_redirect, name='login_redirect'),
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('modules.accounts.urls', namespace='accounts')),
    path(r'home/', include('modules.home.urls', namespace='home')),
    path(r'business/', include('modules.business.urls', namespace='business')),
    path(r'items/', include('modules.items.urls', namespace='items')),
    path(r'todolist/', include('modules.todolist.urls', namespace='todolist')),
    path(r'partners/', include('modules.partners.urls', namespace='partners')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/items/urls.py
from django.urls import path, include
from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView,
    ItemsViewSet

)

from . import views

from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'v1/items/', views.ItemsViewSet)


app_name = 'items'
urlpatterns = [
    path(r'create/',  ItemCreateView.as_view(), name='create'),
    path(r'<int:pk>/edit/', ItemUpdateView.as_view(), name='edit'),
    path(r'<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path(r'', ItemListView.as_view(), name='list'),
    path(r'api/', include(router.urls)),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

modules/items/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from modules.business.models import B2cProfile



class Item(models.Model):
    # associations
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    business      	= models.ForeignKey(B2cProfile, on_delete=models.CASCADE)
    name            = models.CharField(max_length=120)
    description     = models.TextField(max_length = 280)
    extra_info      = models.TextField(max_length = 280)
    politicas       = models.TextField(max_length = 280)
    price           = models.IntegerField(default=0)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self): 
         
        return reverse('items:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

modules/items/forms.py
from django import forms

from modules.business.models import B2cProfile

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [



            'name',
            'business',
            'description',
            'extra_info',
            'politicas',
            'price',
      
           
        ]

    def __init__(self, user=None, *args, **kwargs):
        #print(kwargs.pop('user'))
        print(user)
        print(kwargs)
        super(ItemForm, self).__init__(*args,**kwargs)
        self.fields['business'].queryset = B2cProfile.objects.filter(owner=user)

modules/items/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.models import User

from .forms import ItemForm
from .models import Item

from .serializers import ItemsSerializer
from rest_framework import viewsets

class ItemListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemDetailView(DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'items/item_form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Item'
        return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'items/item_update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs



# ----------------------API---------------------------------



class ItemsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Item.objects.all()
    serializer_class = ItemsSerializer

templates/items/item_detail.html
{% extends "base.html" %}


{% block head_title %}Menu Items | {{ block.super}}{% endblock head_title %}

{% block body %}
<div class="container">
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h2>{{ object.name }}</h2>
{% if user == item.user %}
<a class="text-muted"  href="/items/{{item.pk}}/edit/">Edit</a>
{% endif %}
<img class="card-img-top" src="http://eee.pes.edu/wp-content/uploads/2016/03/default.jpg" style="height: 500px">

<hr>
<p>Price: {{ object.price }}</p>
<p>Location: {{ object.business }}</p>
<p>Dsscription: {{ object.description }}</p>
<p>Extra Info: {{ object.extra_info }}</p>
<p>Politics: {{ object.politicas }}</p>
</div>
</div>
</div>

{% endblock %}

templates/items/item_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}New Base Book{% endblock title %}
{% block body %}

<div class="container">
<h4 class="text-muted">Agregar Item</h4>


<hr>
<div class="d-flex justify-content-center">
<form method = 'POST'>{% csrf_token %}

  {{ form.as_p}}
  <!-- <input type="text" name="name" placeholder="Your title"><br/>
  <input type="text" name="location" placeholder="Location"><br/>
  <input type="text" name="category" placeholder="Category"><br/> -->
  <button type="submit">Save</button>
</form>
</div>
</div>
{% endblock  %}

templates/items/item_list.html
{% block content %}

<div class='container'>
<h3> Products <small><a class="text-muted" href='{% url "items:create" %}'>Add</a></small></h3>

<ul>
{% for obj in object_list %}
    <li><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a><br/>
        {% if obj.contents %}
        Contents
        <ul>    
            {% for item in obj.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}

        </ul>
        {% endif %}

         {% if obj.excludes %}
        Excludes
        <ul>    
            {% for item in obj.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}

        </ul>
        {% endif %}


    </li>
    {% empty %}
    <li><a class="text-muted" href='{% url "items:create" %}'>Add Item</a></li>
</ul>
</div>

{% endfor %}
</ul>
{% endblock %}

templates/items/item_update.html
{% extends "base.html" %}

{% block body %}

<div class="container">


<hr>
<div class="d-flex justify-content-center">
<form method = 'POST'>{% csrf_token %}

  {{ form.as_p}}
  <!-- <input type="text" name="name" placeholder="Your title"><br/>
  <input type="text" name="location" placeholder="Location"><br/>
  <input type="text" name="category" placeholder="Category"><br/> -->
  <button type="submit">Save</button>
</form>
</div>
</div>
{% endblock  %}